version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  frontend:
    build:
      context: ./frontend
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"

